apiVersion: v1
kind: Service
metadata:
  name: alm-service-broker
  namespace: {{ .Values.namespace }}
  labels:
    app: alm-service-broker
spec:
  type: ClusterIP
  ports:
    - name: healthz
      port: {{ .Values.servicebroker.service.internalPort }}
    - name: broker
      port: {{ .Values.servicebroker.service.brokerPort }}
  selector:
    app: alm-service-broker
